### ISSUE TITLE
Error using the allennlp git version mentioned in requirements.txt

### ISSUE THREAD

**Issue by ap229997** [rowanz/swagaf#2]
<img width="1279" alt="error" src="https://user-images.githubusercontent.com/19525041/46590419-0afa4080-caee-11e8-827c-3c0b3708b58e.png">
It seems that the pytorch 0.3 is not supported? Can you tell whether this is the case or am I missing something else while installing?

**Comment by rowanz** [comment]
hey! I'm not sure how you get this error, as when I try reinstalling a fresh virtualenv using the provided instructions (or, the Dockerenv) I'm not able to replicate it and pytorch 0.3 installs normally. Is it possible you're using Python2 or have packages already installed that conflict with the installation?

**Comment by ap229997** [comment]
I think the issue is the python3 version (3.6) that I am using. I will shift to python 3.1 and try again.

**Comment by rowanz** [comment]
My python version is 3.6. Could you try creating a new virtualenv or
condaenv? It should work (at least it does so inside the docker container)

**Comment by ap229997** [comment]
Installing through requirements.txt still doesn't work, but dockerfile does. 
Thanks for your help.
