### ISSUE TITLE
Is the argument of cross_entropy correct?

### ISSUE THREAD

**Issue by marukaz** [rowanz/swagaf#3]
It seems that the targets of cross_entropy function are all 0's.
https://github.com/rowanz/swagaf/blob/0613674cca3612664c3a77a7d26a888ca7d3b127/create_swag/generate_candidates/classifiers.py#L319-L320
The same code is seen in the [rebalance_dataset_mlp.py](https://github.com/rowanz/swagaf/blob/master/create_swag/generate_candidates/rebalance_dataset_mlp.py). Are these expected arguments?

**Comment by rowanz** [comment]
I believe so - reason being is that for v, the correct ending is always the 0-th index, and the wrong endings are the remaining indices.

**Comment by marukaz** [comment]
I understood. Thanks!
